language: python

python:
- "3.5"
- "pypy3.5"
- "3.6"
- "pypy3.6"

services:
- docker

install:
- docker pull redis
- docker run -p 6379:6379 -v $PWD/redis-data:/data -d redis redis-server --appendonly yes
- docker ps -a
- pip install -r requirements-dev.txt

script:
- python -m pytest --cov=./ --cov-report term-missing --cov-config=.coveragerc ./tests

after_success:
- codecov

branches:
  only:
  - master
  - dev
